### ISSUE TITLE
error downloading complete files

### ISSUE THREAD

**Issue by LINGARAJUg** [ComputerElite/Oculus-downgrader#13]
i was able to login, search and pick the version i want and start the download and it always stopped short of complete with 4-5 segments left and wont proceed further.

**Comment by ComputerElite** [comment]
Are you downloading echo VR? An old version of it in particular?

**Comment by LINGARAJUg** [comment]
Yes, I was trying to download the one from most recent. 34.4.3xxxxx.1,
can't remember but it said some kind of net or SSL error.

**Comment by ComputerElite** [comment]
You can try to download it again. Usually that works unless some files are gone from Oculus' servers. To check if that's the case simply search for 410 in your log. That's the error code for 'gone' meaning it doesn't exist

**Comment by LINGARAJUg** [comment]
I have tried several times on 2 different days but it always ended up with
2 to 3 pieces missing, haven't checked the log file yet, will take a look,
thanks.

**Comment by ComputerElite** [comment]
Feel free to send the log here too

**Comment by LINGARAJUg** [comment]
ok tried downloading 3 times just now, all ways ended up with 2 segments missing, attaching log, the cmd screen keeps flickering as if trying to attempt or refresh the download.
![PXL_20231114_143500381 MP](https://github.com/ComputerElite/Oculus-downgrader/assets/42902475/28c41329-61e8-4116-845e-5ae3c8ffd2d6)

[Log.log](https://github.com/ComputerElite/Oculus-downgrader/files/13349940/Log.log)

**Comment by ComputerElite** [comment]
I'll take a look at this later and tell you my findings

**Comment by LINGARAJUg** [comment]
after looking at the cmd window there are atleast 50 instances of download attempts and it keeps duplicating it but just stuck there. thank you.

**Comment by ComputerElite** [comment]
From that log it is not apparent to me what the issue is. I'll try downloading it myself
