### ISSUE TITLE
Application is not opening

### ISSUE THREAD

**Issue by RealNexTech** [ComputerElite/Oculus-downgrader#15]
I downloaded the file and extract it, but when I try to run the application, the screen for it opens for a split second then closes it self.

**Comment by ComputerElite** [comment]
You'll need to install the dotnet 6 runtime as described in the readme file

**Comment by RealNexTech** [comment]
Its saying manifest does not work, and I redownload the game. I'm trying downgrade echo vr

**Comment by AltyFox** [comment]
> Its saying manifest does not work, and saying is the game installed. I redownload the game. I'm trying downgrade echo vr 

You can't downgrade echo VR. Oculus changed their API, we have no more access to download.

**Comment by ComputerElite** [comment]
You can downgrade EchoVR with the newest release again since a few weeks ago
