### ISSUE TITLE
Crashes after searching for a Term

### ISSUE THREAD

**Issue by BL00DY-C0D3** [ComputerElite/Oculus-downgrader#16]
Hey,
if i search for a term, after login in of cours  i get the following error:

An unhandled exception has occured. Check the log for more info and send it to ComputerElite for the (probably) bug to get fixed. Press any key to close out.

Dont know if the Application creates logs. I can send you if you need them.

**Comment by ComputerElite** [comment]
Yes, it creates a log in the folder it's in. I need that to debug the issue

**Comment by BL00DY-C0D3** [comment]
[Log.log](https://github.com/ComputerElite/Oculus-downgrader/files/13940750/Log.log)
Here it is.

**Comment by ComputerElite** [comment]
Thanks! Try your luck with the newest build I just published. Simply open Oculus Downgrader and allow it to update. Report back how it goes and if it doesn't work send your log file again.

**Comment by BL00DY-C0D3** [comment]
Thanks, it works now!
