### ISSUE TITLE
Echo Vr Will not get past a white screen

### ISSUE THREAD

**Issue by EXHOONE** [ComputerElite/Oculus-downgrader#19]
I got a old version of echo and cant get past a white screen after bypassing the entitlement screen. I also noticed that when downloading the old version it is missing a few files sometimes more than others where i retry.

**Comment by ComputerElite** [comment]
Just starting the game on a old version won't make it magically work again. You'll need to mod your game in order to play online.
About the other bug, yes. I'm aware it exists but have not found a way to fix it yet

**Comment by EXHOONE** [comment]
The community has made a way to play online again but you should be able to open the main menu or at least open it in vr rather than just crashing as it begins to load.
Do you know if it is certain files that wont download or is it random?

**Comment by ComputerElite** [comment]
If oculus Downgrader finishes the download the missing files are almost always the same

**Comment by ComputerElite** [comment]
As oculus apparently doesn't have some files anymore

**Comment by EXHOONE** [comment]
are you aware of anywhere i could get the files that could be missing or just files in general.

**Comment by ComputerElite** [comment]
Nope
