### ISSUE TITLE
MSEdge crashing instantly, "Unhandeled Exception" 

### ISSUE THREAD

**Issue by wil-sys** [ComputerElite/Oculus-downgrader#7]
Right after I press Y to sign in, and press a button to open MS Edge it immediately crashes with red text saying "Unhandled exception" after MSEdge Driver starts.
(I had to change the file to .txt to upload)
[Log.log.txt](https://github.com/ComputerElite/Oculus-downgrader/files/8144900/Log.log.txt)

**Comment by ComputerElite** [comment]
Same as issue #5 . Either downgrade your browser or log in without oculus/facebook

**Comment by wil-sys** [comment]
> 

I did downgrade my browser, twice. i did not know not logging in was an option. Thanks.
