### ISSUE TITLE
Hash Doesnt Match, Cant repair

### ISSUE THREAD

**Issue by TungstenWolf** [ComputerElite/Oculus-downgrader#8]
Hash of WindowsNoEditor\WrathGame\Content\Paks\pakchunk19-WindowsNoEditor.pak doesn't match with the one in the manifest! Checked 126.02 GB of 132.97 GB
And then it says it cant access that pak because its open in another process
ive tried running it as admin, same problem

**Comment by ComputerElite** [comment]
Try restarting your pc and making sure oculus isn't open

**Comment by TungstenWolf** [comment]
I just restarted, made sure that no oculus service was running and checked task manager to confirm, ran the program with the same commands as last time and its giving me the same error and some files

**Comment by TungstenWolf** [comment]
Search term: Asgard's Wrath
Requesting results

Results:

   - Asgard's Wrath
Result is exact match. Auto selecting

  - Fetching versions from OculusDB
Date is in format DD-MM-YYYY
Versions of Asgard's Wrath

16.07.2019     0.0.855698
07.10.2019     0.0.874586
09.11.2019     1.1.0
12.12.2019     1.2.0
15.01.2020     1.3.0
17.03.2020     1.4.0
18.05.2021     1.5.0
23.09.2021     1.6.0
Which version do you want?: 1.4.0

Version: 1.4.0 (3958587334151464)
Changelog:

Do you want to download this version? (Y/n): y
Seems like you already have version 1.4.0 (partially) downloaded. Do you want to download it again/resume the download? (Y/n): y
Do you want to download a completly fresh copy (n) or repair the existing one (which resumes failed downloads and repair any corrupted files; Y)? (Y/n): y
Validating and repairing version
Downloading manifest
Downloading https://securecdn.oculus.com/binaries/download/?id=3958587334151464&access_token=&get_manifest=1
  ██████████████████████████████ 732.44 KB / 732.44 KB   Finished
Success
Download of Manifest succeeded
Validating and repairing files of C:\Users\zanev\Desktop\Oculus Downgrader\apps\1180401875303371\3958587334151464\
Loading manifest
Validating WindowsNoEditor\Manifest_NonUFSFiles_Win64.txt
Hash checks out. Checked 2.71 KB of 132.97 GB (1.942244348529616E-06 %)
Validating WindowsNoEditor\Manifest_DebugFiles_Win64.txt
Hash checks out. Checked 3.7 KB of 132.97 GB (2.6510619759050112E-06 %)
Validating WindowsNoEditor\WrathGame\Content\Splash\Splash.bmp
Hash checks out. Checked 355.31 KB of 132.97 GB (0.000254838848183687 %)
Validating WindowsNoEditor\WrathGame.exe
Hash checks out. Checked 799.81 KB of 132.97 GB (0.0005736442847619518 %)
Validating WindowsNoEditor\WrathGame\Binaries\Win64\WrathGame-Win64-Shipping.exe
Hash checks out. Checked 61.5 MB of 132.97 GB (0.045170902888034825 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk10-WindowsNoEditor.pak
Hash checks out. Checked 479.71 MB of 132.97 GB (0.35231323009340876 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk103-WindowsNoEditor.pak
Hash checks out. Checked 2.91 GB of 132.97 GB (2.1857843215431085 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk104-WindowsNoEditor.pak
Hash checks out. Checked 6.62 GB of 132.97 GB (4.978679238722207 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk13-WindowsNoEditor.pak
Hash checks out. Checked 9.73 GB of 132.97 GB (7.318822888445709 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk102-WindowsNoEditor.pak
Hash checks out. Checked 16.32 GB of 132.97 GB (12.270240824715065 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk81-WindowsNoEditor.pak
Hash checks out. Checked 17.28 GB of 132.97 GB (12.992905754265188 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\PhysX3\Win64\VS2015\ApexFramework_x64.dll
Hash checks out. Checked 17.28 GB of 132.97 GB (12.993637321296255 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\Oculus\OVRPlugin\OVRPlugin\Win64\OVRPlugin.dll
Hash checks out. Checked 17.3 GB of 132.97 GB (13.01146741298578 %)
Validating WindowsNoEditor\Engine\Plugins\Runtime\Nvidia\Ansel\Binaries\ThirdParty\AnselSDK64.dll
Hash checks out. Checked 17.3 GB of 132.97 GB (13.011937227395148 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk112-WindowsNoEditor.pak
Hash checks out. Checked 17.8 GB of 132.97 GB (13.384548894499387 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk101-WindowsNoEditor.pak
Hash checks out. Checked 24.96 GB of 132.97 GB (18.77013131009778 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk105-WindowsNoEditor.pak
Hash checks out. Checked 32.91 GB of 132.97 GB (24.750086096713467 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk24-WindowsNoEditor.pak
Hash checks out. Checked 34.09 GB of 132.97 GB (25.63466455029123 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\Vorbis\Win64\VS2015\libvorbisfile_64.dll
Hash checks out. Checked 34.09 GB of 132.97 GB (25.63469108752667 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\PhysX3\Win64\VS2015\PxFoundation_x64.dll
Hash checks out. Checked 34.09 GB of 132.97 GB (25.634729458934675 %)
Validating WindowsNoEditor\Engine\Plugins\Runtime\FMODStudio\Binaries\Win64\OculusSpatializerFMOD.dll
Hash checks out. Checked 34.09 GB of 132.97 GB (25.635996729596293 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk0-WindowsNoEditor.pak
Hash of WindowsNoEditor\WrathGame\Content\Paks\pakchunk0-WindowsNoEditor.pak doesn't match with the one in the manifest! Checked 42.51 GB of 132.97 GB (31.968296268377838 %)
Hash of WindowsNoEditor\WrathGame\Content\Paks\pakchunk0-WindowsNoEditor.pak is unable to get Computed (The process cannot access the file 'C:\Users\zanev\Desktop\Oculus Downgrader\apps\1180401875303371\3958587334151464\WindowsNoEditor\WrathGame\Content\Paks\pakchunk0-WindowsNoEditor.pak' because it is being used by another process.). Checked 42.51 GB of 132.97 GB (31.968296268377838 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk14-WindowsNoEditor.pak
Hash checks out. Checked 42.94 GB of 132.97 GB (32.2919118534415 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk110-WindowsNoEditor.pak
Hash checks out. Checked 51.72 GB of 132.97 GB (38.89919844730366 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk106-WindowsNoEditor.pak
Hash of WindowsNoEditor\WrathGame\Content\Paks\pakchunk106-WindowsNoEditor.pak doesn't match with the one in the manifest! Checked 61.16 GB of 132.97 GB (45.995081610370136 %)
Hash of WindowsNoEditor\WrathGame\Content\Paks\pakchunk106-WindowsNoEditor.pak is unable to get Computed (The process cannot access the file 'C:\Users\zanev\Desktop\Oculus Downgrader\apps\1180401875303371\3958587334151464\WindowsNoEditor\WrathGame\Content\Paks\pakchunk106-WindowsNoEditor.pak' because it is being used by another process.). Checked 61.16 GB of 132.97 GB (45.995081610370136 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk17-WindowsNoEditor.pak
Hash checks out. Checked 62.19 GB of 132.97 GB (46.76700177395028 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk21-WindowsNoEditor.pak
Hash checks out. Checked 63.59 GB of 132.97 GB (47.82297550269683 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\Ogg\Win64\VS2015\libogg_64.dll
Hash checks out. Checked 63.59 GB of 132.97 GB (47.823009929380646 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\PhysX3\Win64\VS2015\PhysX3Cooking_x64.dll
Hash checks out. Checked 63.59 GB of 132.97 GB (47.82318206279972 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk82-WindowsNoEditor.pak
Hash checks out. Checked 65.87 GB of 132.97 GB (49.53748291048186 %)
Validating WindowsNoEditor\Engine\Plugins\GameWorks\Flex\Binaries\ThirdParty\Win64\nvToolsExt64_1.dll
Hash checks out. Checked 65.87 GB of 132.97 GB (49.5375166199431 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\PhysX3\Win64\VS2015\APEX_Clothing_x64.dll
Hash checks out. Checked 65.87 GB of 132.97 GB (49.538370832035255 %)
Validating WindowsNoEditor\Engine\Plugins\GameWorks\Flex\Binaries\ThirdParty\Win64\amd_ags_x64.dll
Hash checks out. Checked 65.87 GB of 132.97 GB (49.538447216239966 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk83-WindowsNoEditor.pak
Hash checks out. Checked 66.88 GB of 132.97 GB (50.29428257713524 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\PhysX3\Win64\VS2015\APEX_Legacy_x64.dll
Hash checks out. Checked 66.88 GB of 132.97 GB (50.29661462635242 %)
Validating WindowsNoEditor\Engine\Plugins\GameWorks\Flex\Binaries\ThirdParty\Win64\NvFlexDebugD3D_x64.dll
Hash checks out. Checked 66.88 GB of 132.97 GB (50.29820829492402 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk12-WindowsNoEditor.pak
Hash checks out. Checked 74.8 GB of 132.97 GB (56.255412052189044 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk109-WindowsNoEditor.pak
Hash checks out. Checked 78.7 GB of 132.97 GB (59.18402542705725 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk25-WindowsNoEditor.pak
Hash checks out. Checked 79.96 GB of 132.97 GB (60.13365700380366 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\Vorbis\Win64\VS2015\libvorbis_64.dll
Hash checks out. Checked 79.96 GB of 132.97 GB (60.13485763440172 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\PhysX3\Win64\VS2015\PxPvdSDK_x64.dll
Hash checks out. Checked 79.96 GB of 132.97 GB (60.13499032057892 %)
Validating WindowsNoEditor\Engine\Plugins\Runtime\FMODStudio\Binaries\Win64\fmodstudio64.dll
Hash checks out. Checked 79.96 GB of 132.97 GB (60.13598044634989 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk107-WindowsNoEditor.pak
Hash of WindowsNoEditor\WrathGame\Content\Paks\pakchunk107-WindowsNoEditor.pak doesn't match with the one in the manifest! Checked 93.09 GB of 132.97 GB (70.00961648707604 %)
Hash of WindowsNoEditor\WrathGame\Content\Paks\pakchunk107-WindowsNoEditor.pak is unable to get Computed (The process cannot access the file 'C:\Users\zanev\Desktop\Oculus Downgrader\apps\1180401875303371\3958587334151464\WindowsNoEditor\WrathGame\Content\Paks\pakchunk107-WindowsNoEditor.pak' because it is being used by another process.). Checked 93.09 GB of 132.97 GB (70.00961648707604 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk108-WindowsNoEditor.pak
Hash of WindowsNoEditor\WrathGame\Content\Paks\pakchunk108-WindowsNoEditor.pak doesn't match with the one in the manifest! Checked 106.99 GB of 132.97 GB (80.46162696341584 %)
Hash of WindowsNoEditor\WrathGame\Content\Paks\pakchunk108-WindowsNoEditor.pak is unable to get Computed (The process cannot access the file 'C:\Users\zanev\Desktop\Oculus Downgrader\apps\1180401875303371\3958587334151464\WindowsNoEditor\WrathGame\Content\Paks\pakchunk108-WindowsNoEditor.pak' because it is being used by another process.). Checked 106.99 GB of 132.97 GB (80.46162696341584 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk111-WindowsNoEditor.pak
Hash checks out. Checked 113.83 GB of 132.97 GB (85.60519842578202 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk18-WindowsNoEditor.pak
Hash checks out. Checked 116.8 GB of 132.97 GB (87.83731525381694 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk84-WindowsNoEditor.pak
Hash checks out. Checked 116.9 GB of 132.97 GB (87.91492206527757 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\PhysX3\Win64\VS2015\APEX_Destructible_x64.dll
Hash checks out. Checked 116.9 GB of 132.97 GB (87.91632997320107 %)
Validating WindowsNoEditor\Engine\Plugins\GameWorks\Flex\Binaries\ThirdParty\Win64\NvFlexExtDebugD3D_x64.dll
Hash checks out. Checked 116.9 GB of 132.97 GB (87.9170633332886 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk20-WindowsNoEditor.pak
Hash of WindowsNoEditor\WrathGame\Content\Paks\pakchunk20-WindowsNoEditor.pak doesn't match with the one in the manifest! Checked 121.54 GB of 132.97 GB (91.40491807298031 %)
Hash of WindowsNoEditor\WrathGame\Content\Paks\pakchunk20-WindowsNoEditor.pak is unable to get Computed (The process cannot access the file 'C:\Users\zanev\Desktop\Oculus Downgrader\apps\1180401875303371\3958587334151464\WindowsNoEditor\WrathGame\Content\Paks\pakchunk20-WindowsNoEditor.pak' because it is being used by another process.). Checked 121.54 GB of 132.97 GB (91.40491807298031 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\WaveWorks\win64\gfsdk_waveworks.win64.lib
Hash checks out. Checked 121.54 GB of 132.97 GB (91.40494034890501 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\PhysX3\Win64\VS2015\PhysX3Common_x64.dll
Hash checks out. Checked 121.54 GB of 132.97 GB (91.40605921612901 %)
Validating WindowsNoEditor\Engine\Plugins\GameWorks\Flex\Binaries\ThirdParty\Win64\NvFlexReleaseD3D_x64.dll
Hash checks out. Checked 121.54 GB of 132.97 GB (91.40703392161453 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk19-WindowsNoEditor.pak
Hash of WindowsNoEditor\WrathGame\Content\Paks\pakchunk19-WindowsNoEditor.pak doesn't match with the one in the manifest! Checked 126.02 GB of 132.97 GB (94.77659489925183 %)
Hash of WindowsNoEditor\WrathGame\Content\Paks\pakchunk19-WindowsNoEditor.pak is unable to get Computed (The process cannot access the file 'C:\Users\zanev\Desktop\Oculus Downgrader\apps\1180401875303371\3958587334151464\WindowsNoEditor\WrathGame\Content\Paks\pakchunk19-WindowsNoEditor.pak' because it is being used by another process.). Checked 126.02 GB of 132.97 GB (94.77659489925183 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\WaveWorks\win64\gfsdk_waveworks.win64.dll
Hash checks out. Checked 126.02 GB of 132.97 GB (94.77686206466268 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\PhysX3\Win64\VS2015\NvCloth_x64.dll
Hash checks out. Checked 126.02 GB of 132.97 GB (94.77704818392206 %)
Validating WindowsNoEditor\Engine\Plugins\GameWorks\Flex\Binaries\ThirdParty\Win64\NvFlexExtReleaseD3D_x64.dll
Hash checks out. Checked 126.02 GB of 132.97 GB (94.77734977601673 %)
Validating WindowsNoEditor\WrathGame\Content\Paks\pakchunk23-WindowsNoEditor.pak
Hash checks out. Checked 132.96 GB of 132.97 GB (99.99729126324276 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\Windows\DirectX\x64\WinPixEventRuntime.dll
Hash checks out. Checked 132.96 GB of 132.97 GB (99.9973226081108 %)
Validating WindowsNoEditor\Engine\Binaries\ThirdParty\PhysX3\Win64\VS2015\PhysX3_x64.dll
Hash checks out. Checked 132.97 GB of 132.97 GB (99.99877175633264 %)
Validating WindowsNoEditor\Engine\Plugins\Runtime\FMODStudio\Binaries\Win64\fmod64.dll
Hash checks out. Checked 132.97 GB of 132.97 GB (100 %)
Only 55 out of 61 files are valid! The files were unable to get repaired. You can reinstall the version by simply downloading it again via the tool.
Failed to repair/download game

**Comment by ComputerElite** [comment]
Ig you could ignore the error and just start the game

**Comment by TungstenWolf** [comment]
Ive tried and it just never opens, im looking at othe ways to open the game, maybe if  you could run as system instead of admin, so its higher than other programs? i have no idea rn

**Comment by TungstenWolf** [comment]
ITs the same files as well, maybe theres a way to just download those from oculus db

**Comment by ComputerElite** [comment]
I mean the download didn't fail. It probably downloaded the right files but it just can't validate. In 4 - 5 hours we could hop on a discord call if you want and debug the issue

**Comment by ComputerElite** [comment]
ComputerElite#0486 on discord

**Comment by TungstenWolf** [comment]
Damn im gonna be at work tho, maybe tomorrow, im just gonna keep troubleshooting

**Comment by ComputerElite** [comment]
Sure I got time tomorrow. Should be awake starting 12 am GMT

**Comment by TungstenWolf** [comment]
kk

**Comment by TungstenWolf** [comment]
Ight so i fixed it, for those wondering you need to delete the files it cant validate so it can redownload them, should work
