### ISSUE TITLE
Fetching Versions from OculusDB crashing

### ISSUE THREAD

**Issue by JakkFish** [ComputerElite/Oculus-downgrader#9]
I was trying to use this application to see if I
 can get an older version of Meta Quest Browser for my oculus quest 2 and while it was loading it wouldnt stop and then it would just close and after a few times of trying i found a weird error that appears then dissapears quickly
 I'm wondering if you can help with this i also tried doing this for beat saber and it also closed

![Screenshot 2022-11-20 030914](https://user-images.githubusercontent.com/84202439/202894436-8c5716a0-dc31-4711-b05c-ac9f2a7284c8.png)

**Comment by ComputerElite** [comment]
OculusDB had some server problems which should be resolved now. Try again

**Comment by JakkFish** [comment]
Thanks so much, no more issues
